// Curated display names, sector labels and short factual company descriptions
// for well-known NSE stocks. Text only — no prices or financial figures
// (those are always fetched live). Extends the generated universe.

export type CuratedInfo = { name: string; sector: string; about: string };

export const CURATED_INFO: Record<string, CuratedInfo> = {
  "RELIANCE": { name: "Reliance Industries", sector: "Energy", about: "India's largest conglomerate with interests in oil-to-chemicals, telecom (Jio), and retail." },
  "TCS": { name: "Tata Consultancy Services", sector: "IT", about: "India's largest IT services company and part of the Tata Group." },
  "INFY": { name: "Infosys", sector: "IT", about: "Global leader in next-generation digital services and consulting." },
  "HDFCBANK": { name: "HDFC Bank", sector: "Banking", about: "India's largest private sector bank by assets and market capitalisation." },
  "ICICIBANK": { name: "ICICI Bank", sector: "Banking", about: "Leading Indian multinational private bank." },
  "SBIN": { name: "State Bank of India", sector: "Banking", about: "India's largest public sector bank." },
  "BHARTIARTL": { name: "Bharti Airtel", sector: "Telecom", about: "Leading global telecommunications company." },
  "HINDUNILVR": { name: "Hindustan Unilever", sector: "FMCG", about: "FMCG major with iconic brands like Surf, Lifebuoy, Dove and Lipton." },
  "ITC": { name: "ITC Ltd", sector: "FMCG", about: "Multi-business conglomerate spanning FMCG, hotels, paperboards, packaging and agribusiness." },
  "LT": { name: "Larsen & Toubro", sector: "Infra", about: "India's largest engineering & construction company." },
  "KOTAKBANK": { name: "Kotak Mahindra Bank", sector: "Banking", about: "Leading private sector bank in India." },
  "AXISBANK": { name: "Axis Bank", sector: "Banking", about: "Third largest private sector bank in India." },
  "MARUTI": { name: "Maruti Suzuki India", sector: "Auto", about: "India's largest passenger car manufacturer." },
  "ASIANPAINT": { name: "Asian Paints", sector: "Paints", about: "India's leading paint and decorative coatings company." },
  "SUNPHARMA": { name: "Sun Pharma", sector: "Pharma", about: "India's largest pharmaceutical company by revenue." },
  "TITAN": { name: "Titan Company", sector: "Consumer", about: "Watches, jewellery (Tanishq) and eyewear major from the Tata Group." },
  "BAJFINANCE": { name: "Bajaj Finance", sector: "Finance", about: "India's leading non-banking financial company." },
  "WIPRO": { name: "Wipro", sector: "IT", about: "Leading global IT, consulting and business process services company." },
  "ULTRACEMCO": { name: "UltraTech Cement", sector: "Cement", about: "India's largest cement manufacturer and exporter." },
  "NESTLEIND": { name: "Nestle India", sector: "FMCG", about: "Indian subsidiary of Nestle, with Maggi, Nescafe and KitKat among its brands." },
  "POWERGRID": { name: "Power Grid", sector: "Power", about: "India's principal electric power transmission company." },
  "NTPC": { name: "NTPC", sector: "Power", about: "India's largest power generation company." },
  "TATAMOTORS": { name: "Tata Motors", sector: "Auto", about: "Leading Indian automotive manufacturer, parent of Jaguar Land Rover." },
  "ADANIENT": { name: "Adani Enterprises", sector: "Infra", about: "Flagship company of the Adani Group with diverse business interests." },
  "ADANIPORTS": { name: "Adani Ports & SEZ", sector: "Infra", about: "India's largest commercial port operator." },
  "HCLTECH": { name: "HCL Technologies", sector: "IT", about: "Multinational IT services and consulting company." },
  "M&M": { name: "Mahindra & Mahindra", sector: "Auto", about: "Major Indian SUV and tractor manufacturer." },
  "TECHM": { name: "Tech Mahindra", sector: "IT", about: "Indian multinational IT services and consulting company." },
  "ONGC": { name: "ONGC", sector: "Energy", about: "India's largest crude oil and natural gas company." },
  "INDUSINDBK": { name: "IndusInd Bank", sector: "Banking", about: "Private sector bank focused on retail and corporate banking." },
  "BAJAJFINSV": { name: "Bajaj Finserv", sector: "Finance", about: "Holding company for the financial services businesses of the Bajaj Group." },
  "JSWSTEEL": { name: "JSW Steel", sector: "Metals", about: "Among India's largest steel producers." },
  "TATASTEEL": { name: "Tata Steel", sector: "Metals", about: "One of the world's most geographically diversified steel producers." },
  "GRASIM": { name: "Grasim Industries", sector: "Cement", about: "Flagship of the Aditya Birla Group, into cement, chemicals and viscose fibres." },
  "HDFCLIFE": { name: "HDFC Life", sector: "Insurance", about: "Leading long-term life insurance solutions provider." },
  "SBILIFE": { name: "SBI Life Insurance", sector: "Insurance", about: "One of India's leading life insurance companies." },
  "COALINDIA": { name: "Coal India", sector: "Energy", about: "World's largest coal producer." },
  "DRREDDY": { name: "Dr Reddy's Labs", sector: "Pharma", about: "Multinational pharmaceutical company headquartered in Hyderabad." },
  "CIPLA": { name: "Cipla", sector: "Pharma", about: "Indian multinational pharmaceutical and biotechnology company." },
  "DIVISLAB": { name: "Divi's Labs", sector: "Pharma", about: "Manufacturer of active pharmaceutical ingredients (APIs)." },
  "EICHERMOT": { name: "Eicher Motors", sector: "Auto", about: "Parent of Royal Enfield and Volvo Eicher Commercial Vehicles." },
  "HEROMOTOCO": { name: "Hero MotoCorp", sector: "Auto", about: "World's largest two-wheeler manufacturer by volume." },
  "BAJAJ-AUTO": { name: "Bajaj Auto", sector: "Auto", about: "Major Indian two-wheeler and three-wheeler manufacturer." },
  "BRITANNIA": { name: "Britannia Industries", sector: "FMCG", about: "One of India's leading food companies, famous for biscuits." },
  "BPCL": { name: "Bharat Petroleum", sector: "Energy", about: "Maharatna PSU oil and gas refining and marketing company." },
  "TATACONSUM": { name: "Tata Consumer", sector: "FMCG", about: "Consumer products arm of the Tata Group." },
  "APOLLOHOSP": { name: "Apollo Hospitals", sector: "Healthcare", about: "Largest network of for-profit private hospitals in India." },
  "HINDALCO": { name: "Hindalco", sector: "Metals", about: "Aluminium and copper manufacturing giant from the Aditya Birla Group." },
  "PNB": { name: "Punjab National Bank", sector: "Banking", about: "One of India's largest public sector banks by branch network." },
  "BANKBARODA": { name: "Bank of Baroda", sector: "Banking", about: "Major public sector bank with a large international presence." },
  "CANBK": { name: "Canara Bank", sector: "Banking", about: "Public sector bank headquartered in Bengaluru, among India's oldest." },
  "IDFCFIRSTB": { name: "IDFC First Bank", sector: "Banking", about: "Private bank focused on retail banking and financial inclusion." },
  "FEDERALBNK": { name: "Federal Bank", sector: "Banking", about: "Kerala-based private bank with a strong NRI customer base." },
  "BANDHANBNK": { name: "Bandhan Bank", sector: "Banking", about: "Bank with roots in microfinance, focused on eastern India." },
  "AUBANK": { name: "AU Small Finance Bank", sector: "Banking", about: "Largest small finance bank in India by market cap." },
  "RBLBANK": { name: "RBL Bank", sector: "Banking", about: "Private sector bank with a focus on retail and MSME lending." },
  "YESBANK": { name: "Yes Bank", sector: "Banking", about: "Private bank that underwent a 2020 reconstruction; rebuilding its book." },
  "PFC": { name: "Power Finance Corporation", sector: "Finance", about: "State-owned NBFC financing India's power sector." },
  "RECLTD": { name: "REC Limited", sector: "Finance", about: "State-owned NBFC funding power infrastructure projects." },
  "MUTHOOTFIN": { name: "Muthoot Finance", sector: "Finance", about: "India's largest gold loan NBFC." },
  "CHOLAFIN": { name: "Cholamandalam Investment", sector: "Finance", about: "Vehicle and home loan focused NBFC from the Murugappa Group." },
  "LICHSGFIN": { name: "LIC Housing Finance", sector: "Finance", about: "Housing finance company backed by LIC." },
  "SHRIRAMFIN": { name: "Shriram Finance", sector: "Finance", about: "Diversified NBFC focused on commercial vehicle financing." },
  "ICICIPRULI": { name: "ICICI Prudential Life", sector: "Insurance", about: "Life insurance joint venture between ICICI Bank and Prudential." },
  "ICICIGI": { name: "ICICI Lombard General Insurance", sector: "Insurance", about: "Leading private general insurance company in India." },
  "LICI": { name: "Life Insurance Corporation of India", sector: "Insurance", about: "India's largest life insurer, state-owned." },
  "IEX": { name: "Indian Energy Exchange", sector: "Finance", about: "India's leading electricity spot market exchange." },
  "CDSL": { name: "Central Depository Services", sector: "Finance", about: "One of India's two securities depositories." },
  "BSE": { name: "BSE Limited", sector: "Finance", about: "Asia's oldest stock exchange, now a listed for-profit company." },
  "MCX": { name: "Multi Commodity Exchange", sector: "Finance", about: "India's largest commodity derivatives exchange." },
  "ANGELONE": { name: "Angel One", sector: "Finance", about: "Full-stack digital broking and financial services platform." },
  "IIFL": { name: "IIFL Finance", sector: "Finance", about: "Diversified NBFC offering gold, home and business loans." },
  "SBICARD": { name: "SBI Cards & Payment Services", sector: "Finance", about: "India's second-largest credit card issuer, backed by SBI." },
  "PAYTM": { name: "One 97 Communications (Paytm)", sector: "Finance", about: "Digital payments and financial services platform." },
  "POLICYBZR": { name: "PB Fintech (Policybazaar)", sector: "Finance", about: "Online insurance and lending marketplace." },
  "LTIM": { name: "LTIMindtree", sector: "IT", about: "IT services company formed from the merger of L&T Infotech and Mindtree." },
  "MPHASIS": { name: "Mphasis", sector: "IT", about: "IT services company specialising in BFSI and cloud." },
  "PERSISTENT": { name: "Persistent Systems", sector: "IT", about: "Digital engineering and software services company." },
  "COFORGE": { name: "Coforge", sector: "IT", about: "Global IT solutions provider focused on BFSI and travel." },
  "LTTS": { name: "L&T Technology Services", sector: "IT", about: "Engineering R&D services arm of Larsen & Toubro." },
  "OFSS": { name: "Oracle Financial Services Software", sector: "IT", about: "Banking software subsidiary of Oracle Corporation." },
  "KPITTECH": { name: "KPIT Technologies", sector: "IT", about: "Software focused on mobility and automotive engineering." },
  "TATAELXSI": { name: "Tata Elxsi", sector: "IT", about: "Design and technology services for media, auto and healthcare." },
  "ZENSAR": { name: "Zensar Technologies", sector: "IT", about: "Digital and technology services company under the RPG Group." },
  "HAPPSTMNDS": { name: "Happiest Minds Technologies", sector: "IT", about: "Digital transformation and IT services company." },
  "TVSMOTOR": { name: "TVS Motor Company", sector: "Auto", about: "Two and three-wheeler manufacturer from the TVS Group." },
  "ASHOKLEY": { name: "Ashok Leyland", sector: "Auto", about: "Second-largest commercial vehicle maker in India, Hinduja Group." },
  "BOSCHLTD": { name: "Bosch Limited", sector: "Auto", about: "Auto component manufacturer, Indian arm of Bosch Group." },
  "MOTHERSON": { name: "Samvardhana Motherson", sector: "Auto", about: "Global auto components manufacturer." },
  "BALKRISIND": { name: "Balkrishna Industries", sector: "Auto", about: "Off-highway tyre manufacturer with global exports." },
  "MRF": { name: "MRF Limited", sector: "Auto", about: "India's largest tyre manufacturer by revenue." },
  "APOLLOTYRE": { name: "Apollo Tyres", sector: "Auto", about: "Leading Indian tyre manufacturer with European operations." },
  "EXIDEIND": { name: "Exide Industries", sector: "Auto", about: "Leading lead-acid and lithium battery manufacturer." },
  "TIINDIA": { name: "Tube Investments of India", sector: "Auto", about: "Diversified engineering company under the Murugappa Group." },
  "BHARATFORG": { name: "Bharat Forge", sector: "Auto", about: "Global forging and auto components manufacturer." },
  "SONACOMS": { name: "Sona BLW Precision Forgings", sector: "Auto", about: "EV-focused auto component manufacturer (Sona Comstar)." },
  "UNOMINDA": { name: "UNO Minda", sector: "Auto", about: "Auto components maker specialising in switches and lighting." },
  "LUPIN": { name: "Lupin Limited", sector: "Pharma", about: "Multinational pharmaceutical company known for generics." },
  "AUROPHARMA": { name: "Aurobindo Pharma", sector: "Pharma", about: "Generic drug manufacturer with major US exposure." },
  "ALKEM": { name: "Alkem Laboratories", sector: "Pharma", about: "Domestic-focused pharmaceutical company, strong in acute therapies." },
  "TORNTPHARM": { name: "Torrent Pharmaceuticals", sector: "Pharma", about: "Branded generics pharma company from the Torrent Group." },
  "ZYDUSLIFE": { name: "Zydus Lifesciences", sector: "Pharma", about: "Diversified pharmaceutical company with global generics reach." },
  "BIOCON": { name: "Biocon", sector: "Pharma", about: "Biopharmaceutical company focused on biosimilars." },
  "GLENMARK": { name: "Glenmark Pharmaceuticals", sector: "Pharma", about: "Research-driven pharmaceutical company, strong in dermatology." },
  "LAURUSLABS": { name: "Laurus Labs", sector: "Pharma", about: "API and generics manufacturer, strong in antiretrovirals." },
  "IPCALAB": { name: "Ipca Laboratories", sector: "Pharma", about: "Formulations and API manufacturer, strong in anti-malarials." },
  "ABBOTINDIA": { name: "Abbott India", sector: "Pharma", about: "Indian subsidiary of Abbott Laboratories." },
  "PFIZER": { name: "Pfizer Limited", sector: "Pharma", about: "Indian subsidiary of the global pharma major Pfizer." },
  "MANKIND": { name: "Mankind Pharma", sector: "Pharma", about: "Domestic-focused pharma company known for consumer health brands." },
  "FORTIS": { name: "Fortis Healthcare", sector: "Healthcare", about: "Multi-specialty hospital chain across India." },
  "MAXHEALTH": { name: "Max Healthcare Institute", sector: "Healthcare", about: "Premium hospital chain concentrated in North India." },
  "METROPOLIS": { name: "Metropolis Healthcare", sector: "Healthcare", about: "Diagnostic chain offering pathology and lab testing services." },
  "LALPATHLAB": { name: "Dr Lal PathLabs", sector: "Healthcare", about: "One of India's largest diagnostic chains." },
  "NARAYANHRUD": { name: "Narayana Hrudayalaya", sector: "Healthcare", about: "Multi-specialty hospital chain founded by Dr Devi Shetty." },
  "DABUR": { name: "Dabur India", sector: "FMCG", about: "Ayurvedic and natural consumer products company." },
  "GODREJCP": { name: "Godrej Consumer Products", sector: "FMCG", about: "FMCG company known for soaps, hair care and home care." },
  "MARICO": { name: "Marico Limited", sector: "FMCG", about: "FMCG major behind Parachute, Saffola and Livon." },
  "COLPAL": { name: "Colgate-Palmolive India", sector: "FMCG", about: "Indian subsidiary of the global oral care major." },
  "VBL": { name: "Varun Beverages", sector: "FMCG", about: "PepsiCo's largest bottling partner outside the US." },
  "UBL": { name: "United Breweries", sector: "FMCG", about: "India's largest beer company, maker of Kingfisher." },
  "RADICO": { name: "Radico Khaitan", sector: "FMCG", about: "Premium Indian-made foreign liquor manufacturer." },
  "EMAMILTD": { name: "Emami Limited", sector: "FMCG", about: "FMCG company known for Navratna, Boroplus and Zandu." },
  "PGHH": { name: "Procter & Gamble Hygiene", sector: "FMCG", about: "Indian listed arm of P&G, known for Whisper and Vicks." },
  "GILLETTE": { name: "Gillette India", sector: "FMCG", about: "Personal grooming products, Indian arm of P&G's Gillette." },
  "JYOTHYLAB": { name: "Jyothy Labs", sector: "FMCG", about: "FMCG company known for Ujala, Exo and Margo brands." },
  "BAJAJCON": { name: "Bajaj Consumer Care", sector: "FMCG", about: "FMCG company known for Bajaj Almond Drops hair oil." },
  "IOC": { name: "Indian Oil Corporation", sector: "Energy", about: "India's largest oil refining and marketing PSU." },
  "GAIL": { name: "GAIL India", sector: "Energy", about: "India's largest natural gas transmission and marketing company." },
  "PETRONET": { name: "Petronet LNG", sector: "Energy", about: "Operator of India's largest LNG import terminals." },
  "IGL": { name: "Indraprastha Gas", sector: "Energy", about: "City gas distribution company for the Delhi NCR region." },
  "MGL": { name: "Mahanagar Gas", sector: "Energy", about: "City gas distribution company for Mumbai region." },
  "ADANIGREEN": { name: "Adani Green Energy", sector: "Power", about: "Renewable energy generation arm of the Adani Group." },
  "ADANIPOWER": { name: "Adani Power", sector: "Power", about: "India's largest private thermal power producer." },
  "ADANIENSOL": { name: "Adani Energy Solutions", sector: "Power", about: "Power transmission and distribution arm of the Adani Group." },
  "TATAPOWER": { name: "Tata Power", sector: "Power", about: "Integrated power company spanning generation to distribution." },
  "NHPC": { name: "NHPC Limited", sector: "Power", about: "State-owned hydropower generation company." },
  "SJVN": { name: "SJVN Limited", sector: "Power", about: "State-owned hydro and renewable power generation company." },
  "TORNTPOWER": { name: "Torrent Power", sector: "Power", about: "Integrated power utility across Gujarat and other states." },
  "JSWENERGY": { name: "JSW Energy", sector: "Power", about: "Power generation company under the JSW Group." },
  "CESC": { name: "CESC Limited", sector: "Power", about: "Integrated power utility serving Kolkata and other regions." },
  "VEDL": { name: "Vedanta Limited", sector: "Metals", about: "Diversified natural resources company — zinc, oil, aluminium." },
  "NMDC": { name: "NMDC Limited", sector: "Metals", about: "India's largest iron ore producer, state-owned." },
  "JINDALSTEL": { name: "Jindal Steel & Power", sector: "Metals", about: "Steel and power producer from the O.P. Jindal Group." },
  "SAIL": { name: "Steel Authority of India", sector: "Metals", about: "State-owned integrated steel producer." },
  "NATIONALUM": { name: "National Aluminium Company", sector: "Metals", about: "State-owned aluminium producer and exporter." },
  "HINDZINC": { name: "Hindustan Zinc", sector: "Metals", about: "World's second-largest zinc producer, Vedanta Group." },
  "RATNAMANI": { name: "Ratnamani Metals & Tubes", sector: "Metals", about: "Manufacturer of stainless steel and carbon steel pipes." },
  "APLAPOLLO": { name: "APL Apollo Tubes", sector: "Metals", about: "India's largest structural steel tube manufacturer." },
  "SHREECEM": { name: "Shree Cement", sector: "Cement", about: "One of India's largest cement manufacturers by capacity." },
  "AMBUJACEM": { name: "Ambuja Cements", sector: "Cement", about: "Cement major, part of the Adani Group." },
  "ACC": { name: "ACC Limited", sector: "Cement", about: "Cement manufacturer, part of the Adani-owned Ambuja Group." },
  "DALBHARAT": { name: "Dalmia Bharat", sector: "Cement", about: "Major cement producer with strong presence in East India." },
  "JKCEMENT": { name: "JK Cement", sector: "Cement", about: "Grey and white cement manufacturer from the JK Group." },
  "RAMCOCEM": { name: "The Ramco Cements", sector: "Cement", about: "South India-focused cement manufacturer." },
  "SIEMENS": { name: "Siemens Limited", sector: "Infra", about: "Indian arm of Siemens AG — automation, power and mobility." },
  "ABB": { name: "ABB India", sector: "Infra", about: "Indian arm of ABB Group — electrification and automation." },
  "CUMMINSIND": { name: "Cummins India", sector: "Infra", about: "Engine and power generation equipment manufacturer." },
  "HAVELLS": { name: "Havells India", sector: "Consumer", about: "Electrical equipment and consumer durables manufacturer." },
  "VOLTAS": { name: "Voltas Limited", sector: "Consumer", about: "India's largest air conditioning and cooling appliances brand." },
  "BLUESTARCO": { name: "Blue Star Limited", sector: "Consumer", about: "Air conditioning and commercial refrigeration company." },
  "CGPOWER": { name: "CG Power and Industrial Solutions", sector: "Infra", about: "Power transmission and industrial equipment manufacturer." },
  "THERMAX": { name: "Thermax Limited", sector: "Infra", about: "Energy and environment engineering solutions provider." },
  "BEL": { name: "Bharat Electronics", sector: "Defence", about: "State-owned defence electronics and radar manufacturer." },
  "HAL": { name: "Hindustan Aeronautics", sector: "Defence", about: "State-owned aerospace and defence manufacturer." },
  "BEML": { name: "BEML Limited", sector: "Defence", about: "State-owned manufacturer of earthmoving, rail and defence equipment." },
  "BHEL": { name: "Bharat Heavy Electricals", sector: "Infra", about: "State-owned power plant equipment manufacturer." },
  "IRCTC": { name: "Indian Railway Catering & Tourism Corp", sector: "Infra", about: "Monopoly provider of railway catering, tourism and ticketing." },
  "CONCOR": { name: "Container Corporation of India", sector: "Infra", about: "State-owned container logistics and rail freight company." },
  "GMRINFRA": { name: "GMR Airports Infrastructure", sector: "Infra", about: "Airport infrastructure operator — Delhi and Hyderabad airports." },
  "NBCC": { name: "NBCC (India)", sector: "Infra", about: "State-owned real estate and construction PSU." },
  "RVNL": { name: "Rail Vikas Nigam", sector: "Infra", about: "State-owned railway infrastructure construction company." },
  "IRFC": { name: "Indian Railway Finance Corp", sector: "Finance", about: "State-owned financing arm for Indian Railways." },
  "RAILTEL": { name: "RailTel Corporation of India", sector: "Telecom", about: "Railway-owned telecom infrastructure provider." },
  "IDEA": { name: "Vodafone Idea", sector: "Telecom", about: "Telecom operator formed from the Vodafone-Idea merger." },
  "INDUSTOWER": { name: "Indus Towers", sector: "Telecom", about: "Largest telecom tower infrastructure company in India." },
  "DLF": { name: "DLF Limited", sector: "Realty", about: "India's largest listed real estate developer." },
  "GODREJPROP": { name: "Godrej Properties", sector: "Realty", about: "Real estate developer under the Godrej Group." },
  "OBEROIRLTY": { name: "Oberoi Realty", sector: "Realty", about: "Premium real estate developer focused on Mumbai." },
  "PRESTIGE": { name: "Prestige Estates Projects", sector: "Realty", about: "Bengaluru-headquartered real estate developer." },
  "PHOENIXLTD": { name: "Phoenix Mills", sector: "Realty", about: "Retail-led real estate developer, owner of major mall chains." },
  "LODHA": { name: "Macrotech Developers (Lodha)", sector: "Realty", about: "Mumbai-based real estate developer operating as Lodha." },
  "DMART": { name: "Avenue Supermarts (DMart)", sector: "Retail", about: "Value retail supermarket chain, one of India's most valuable retailers." },
  "TRENT": { name: "Trent Limited", sector: "Retail", about: "Tata Group fashion retailer behind Westside and Zudio." },
  "ABFRL": { name: "Aditya Birla Fashion and Retail", sector: "Retail", about: "Fashion retail conglomerate — Pantaloons, Van Heusen and more." },
  "PAGEIND": { name: "Page Industries (Jockey)", sector: "Retail", about: "Exclusive licensee of Jockey innerwear in India." },
  "RELAXO": { name: "Relaxo Footwears", sector: "Retail", about: "India's largest footwear manufacturer by volume." },
  "BATAINDIA": { name: "Bata India", sector: "Retail", about: "India's largest footwear retailer." },
  "VMART": { name: "V-Mart Retail", sector: "Retail", about: "Value fashion retail chain in Tier 2/3 India." },
  "SHOPERSTOP": { name: "Shoppers Stop", sector: "Retail", about: "Department store chain for apparel and lifestyle products." },
  "ZEEL": { name: "Zee Entertainment Enterprises", sector: "Media", about: "Media and broadcasting company with a large TV network." },
  "SUNTV": { name: "Sun TV Network", sector: "Media", about: "South India-focused broadcaster and media company." },
  "PVRINOX": { name: "PVR INOX", sector: "Media", about: "India's largest multiplex cinema chain." },
  "NETWORK18": { name: "Network18 Media & Investments", sector: "Media", about: "Media conglomerate under the Reliance-Network18 group." },
  "PIDILITIND": { name: "Pidilite Industries", sector: "Chemicals", about: "India's leading adhesives and specialty chemicals company (Fevicol)." },
  "SRF": { name: "SRF Limited", sector: "Chemicals", about: "Diversified chemicals company — fluorochemicals, packaging films." },
  "DEEPAKNTR": { name: "Deepak Nitrite", sector: "Chemicals", about: "Specialty and performance chemicals manufacturer." },
  "UPL": { name: "UPL Limited", sector: "Chemicals", about: "Global agrochemicals and crop protection company." },
  "PIIND": { name: "PI Industries", sector: "Chemicals", about: "Agrochemicals and custom synthesis manufacturer." },
  "AARTIIND": { name: "Aarti Industries", sector: "Chemicals", about: "Specialty chemicals manufacturer serving pharma and agro sectors." },
  "NAVINFLUOR": { name: "Navin Fluorine International", sector: "Chemicals", about: "Fluorochemicals manufacturer, part of the Arvind Mafatlal Group." },
  "ATUL": { name: "Atul Limited", sector: "Chemicals", about: "Diversified specialty and bulk chemicals manufacturer." },
  "TATACHEM": { name: "Tata Chemicals", sector: "Chemicals", about: "Soda ash and specialty chemicals producer, part of Tata Group." },
  "GNFC": { name: "Gujarat Narmada Valley Fertilizers", sector: "Chemicals", about: "State-owned fertilizer and chemicals manufacturer." },
  "COROMANDEL": { name: "Coromandel International", sector: "Chemicals", about: "Fertilizers and crop protection company, Murugappa Group." },
  "INDIGO": { name: "InterGlobe Aviation (IndiGo)", sector: "Airlines", about: "India's largest airline by passenger market share." },
  "BLUEDART": { name: "Blue Dart Express", sector: "Infra", about: "India's leading express air and ground logistics company." },
  "TRIDENT": { name: "Trident Limited", sector: "Textiles", about: "Home textiles and paper manufacturer." },
  "WELSPUNIND": { name: "Welspun Living", sector: "Textiles", about: "Home textiles manufacturer, major global bed linen exporter." },
  "RAYMOND": { name: "Raymond Limited", sector: "Textiles", about: "Textile and apparel conglomerate, iconic Indian menswear brand." },
  "ZOMATO": { name: "Eternal (Zomato)", sector: "New Age", about: "Food delivery and quick-commerce platform (Blinkit parent)." },
  "NYKAA": { name: "FSN E-Commerce Ventures (Nykaa)", sector: "New Age", about: "Beauty and fashion e-commerce platform." },
  "DELHIVERY": { name: "Delhivery Limited", sector: "New Age", about: "Logistics and supply chain services platform." },
  "HUDCO": { name: "Housing & Urban Development Corp", sector: "Finance", about: "State-owned housing and urban infrastructure financier." },
  "IREDA": { name: "Indian Renewable Energy Development Agency", sector: "Finance", about: "State-owned NBFC financing renewable energy projects." },
  "MAZDOCK": { name: "Mazagon Dock Shipbuilders", sector: "Defence", about: "State-owned warship and submarine builder." },
  "COCHINSHIP": { name: "Cochin Shipyard", sector: "Defence", about: "State-owned shipbuilding and ship repair company." },
  "GRSE": { name: "Garden Reach Shipbuilders & Engineers", sector: "Defence", about: "State-owned warship builder for the Indian Navy." },
  "DATAPATTNS": { name: "Data Patterns (India)", sector: "Defence", about: "Defence electronics design and manufacturing company." },
  "SOLARINDS": { name: "Solar Industries India", sector: "Defence", about: "Explosives manufacturer with growing defence ordnance business." },
  "CROMPTON": { name: "Crompton Greaves Consumer Electricals", sector: "Consumer", about: "Consumer electricals — fans, pumps and lighting." },
  "WHIRLPOOL": { name: "Whirlpool of India", sector: "Consumer", about: "Home appliances manufacturer, Indian arm of Whirlpool Corp." },
  "DIXON": { name: "Dixon Technologies", sector: "Consumer", about: "Electronics manufacturing services company (contract manufacturer)." },
  "AMBER": { name: "Amber Enterprises India", sector: "Consumer", about: "Air conditioner and electronics contract manufacturer." },
  "KAYNES": { name: "Kaynes Technology India", sector: "Consumer", about: "Electronics manufacturing services and IoT solutions company." },
  "POLYCAB": { name: "Polycab India", sector: "Consumer", about: "India's largest wires and cables manufacturer." },
  "KEI": { name: "KEI Industries", sector: "Consumer", about: "Wires and cables manufacturer with EPC operations." },
  "UNIONBANK": { name: "Union Bank of India", sector: "Banking", about: "Large public-sector bank headquartered in Mumbai." },
  "INDIANB": { name: "Indian Bank", sector: "Banking", about: "Chennai-based public-sector bank." },
  "IOB": { name: "Indian Overseas Bank", sector: "Banking", about: "Public-sector bank with a strong presence in South India." },
  "BANKINDIA": { name: "Bank of India", sector: "Banking", about: "Public-sector bank, one of India's oldest." },
  "MAHABANK": { name: "Bank of Maharashtra", sector: "Banking", about: "Pune-headquartered public-sector bank." },
  "CENTRALBK": { name: "Central Bank of India", sector: "Banking", about: "Public-sector bank headquartered in Mumbai." },
  "UCOBANK": { name: "UCO Bank", sector: "Banking", about: "Kolkata-based public-sector bank." },
  "KTKBANK": { name: "Karnataka Bank", sector: "Banking", about: "Old private-sector bank based in Mangaluru." },
  "KARURVYSYA": { name: "Karur Vysya Bank", sector: "Banking", about: "Tamil Nadu-based old private-sector bank." },
  "CUB": { name: "City Union Bank", sector: "Banking", about: "Kumbakonam-headquartered old private-sector bank." },
  "SOUTHBANK": { name: "South Indian Bank", sector: "Banking", about: "Kerala-based private-sector bank." },
  "UJJIVANSFB": { name: "Ujjivan Small Finance Bank", sector: "Banking", about: "Small finance bank focused on financial inclusion." },
  "JIOFIN": { name: "Jio Financial Services", sector: "Finance", about: "Financial-services arm demerged from Reliance Industries." },
  "MANAPPURAM": { name: "Manappuram Finance", sector: "Finance", about: "Gold-loan focused non-banking financial company." },
  "M&MFIN": { name: "Mahindra & Mahindra Financial", sector: "Finance", about: "Rural and semi-urban vehicle-finance NBFC." },
  "ABCAPITAL": { name: "Aditya Birla Capital", sector: "Finance", about: "Diversified financial-services holding company." },
  "PEL": { name: "Piramal Enterprises", sector: "Finance", about: "Diversified NBFC and financial-services company." },
  "POONAWALLA": { name: "Poonawalla Fincorp", sector: "Finance", about: "Consumer and MSME lending NBFC." },
  "BAJAJHLDNG": { name: "Bajaj Holdings & Investment", sector: "Finance", about: "Investment holding company of the Bajaj Group." },
  "CANFINHOME": { name: "Can Fin Homes", sector: "Finance", about: "Housing-finance company promoted by Canara Bank." },
  "PNBHOUSING": { name: "PNB Housing Finance", sector: "Finance", about: "Housing-finance company promoted by Punjab National Bank." },
  "HDFCAMC": { name: "HDFC Asset Management", sector: "Finance", about: "One of India's largest mutual-fund asset managers." },
  "NAM-INDIA": { name: "Nippon Life India AMC", sector: "Finance", about: "Asset manager behind Nippon India Mutual Fund." },
  "CAMS": { name: "Computer Age Management Services", sector: "Finance", about: "Registrar and transfer agent for mutual funds." },
  "KFINTECH": { name: "KFin Technologies", sector: "Finance", about: "Investor-solutions and fund-administration platform." },
  "360ONE": { name: "360 One WAM", sector: "Finance", about: "Wealth and asset-management firm (formerly IIFL Wealth)." },
  "STARHEALTH": { name: "Star Health & Allied Insurance", sector: "Insurance", about: "India's largest standalone health insurer." },
  "GICRE": { name: "General Insurance Corporation", sector: "Insurance", about: "State-owned national reinsurer." },
  "NIACL": { name: "New India Assurance", sector: "Insurance", about: "India's largest general insurer, state-owned." },
  "SYNGENE": { name: "Syngene International", sector: "Pharma", about: "Contract research and manufacturing arm of Biocon." },
  "GLAND": { name: "Gland Pharma", sector: "Pharma", about: "Injectable-focused generic pharmaceutical maker." },
  "AJANTPHARM": { name: "Ajanta Pharma", sector: "Pharma", about: "Branded-generics pharmaceutical company." },
  "NATCOPHARM": { name: "Natco Pharma", sector: "Pharma", about: "Specialty and oncology generics maker." },
  "JBCHEPHARM": { name: "JB Chemicals & Pharmaceuticals", sector: "Pharma", about: "Branded-formulations pharmaceutical company." },
  "GRANULES": { name: "Granules India", sector: "Pharma", about: "Active-ingredient and finished-dosage pharma maker." },
  "GLAXO": { name: "GlaxoSmithKline Pharmaceuticals", sector: "Pharma", about: "Indian arm of GSK — vaccines and prescription drugs." },
  "TATATECH": { name: "Tata Technologies", sector: "IT", about: "Engineering and product-development services arm of the Tata Group." },
  "CYIENT": { name: "Cyient", sector: "IT", about: "Engineering, manufacturing and digital-technology services." },
  "SONATSOFTW": { name: "Sonata Software", sector: "IT", about: "IT services and platform-modernisation company." },
  "BIRLASOFT": { name: "Birlasoft", sector: "IT", about: "Enterprise digital and IT services company." },
  "MASTEK": { name: "Mastek", sector: "IT", about: "Digital-transformation and cloud services firm." },
  "INTELLECT": { name: "Intellect Design Arena", sector: "IT", about: "Financial-technology products company." },
  "NAUKRI": { name: "Info Edge (India)", sector: "New Age", about: "Owner of Naukri.com, 99acres and investor in Zomato/PolicyBazaar." },
  "INDIAMART": { name: "IndiaMART InterMESH", sector: "New Age", about: "B2B online marketplace for Indian businesses." },
  "MAPMYINDIA": { name: "C.E. Info Systems (MapmyIndia)", sector: "New Age", about: "Digital maps, geospatial and IoT platform." },
  "AFFLE": { name: "Affle (India)", sector: "New Age", about: "Mobile advertising and consumer-intelligence platform." },
  "OLAELEC": { name: "Ola Electric Mobility", sector: "New Age", about: "Electric two-wheeler manufacturer and EV platform." },
  "SWIGGY": { name: "Swiggy", sector: "New Age", about: "Food-delivery and quick-commerce platform (Instamart)." },
  "CARTRADE": { name: "CarTrade Tech", sector: "New Age", about: "Online automotive marketplace platform." },
  "EASEMYTRIP": { name: "Easy Trip Planners", sector: "New Age", about: "Online travel-booking platform." },
  "ESCORTS": { name: "Escorts Kubota", sector: "Auto", about: "Tractors, construction equipment and railway components." },
  "ARE&M": { name: "Amara Raja Energy & Mobility", sector: "Auto", about: "Automotive and industrial battery manufacturer." },
  "ENDURANCE": { name: "Endurance Technologies", sector: "Auto", about: "Auto-component maker for two-wheelers and cars." },
  "SCHAEFFLER": { name: "Schaeffler India", sector: "Auto", about: "Bearings and precision auto-component manufacturer." },
  "SUNDRMFAST": { name: "Sundram Fasteners", sector: "Auto", about: "Fasteners and precision auto components (TVS Group)." },
  "CEATLTD": { name: "CEAT", sector: "Auto", about: "Tyre manufacturer, part of the RPG Group." },
  "JKTYRE": { name: "JK Tyre & Industries", sector: "Auto", about: "Tyre manufacturer for trucks, buses and passenger cars." },
  "BERGEPAINT": { name: "Berger Paints India", sector: "Paints", about: "India's second-largest decorative-paints company." },
  "KANSAINER": { name: "Kansai Nerolac Paints", sector: "Paints", about: "Decorative and industrial paints maker." },
  "AKZOINDIA": { name: "Akzo Nobel India", sector: "Paints", about: "Maker of Dulux paints and performance coatings." },
  "INDIGOPNTS": { name: "Indigo Paints", sector: "Paints", about: "Fast-growing decorative-paints challenger brand." },
  "PATANJALI": { name: "Patanjali Foods", sector: "FMCG", about: "Edible-oils and FMCG company (formerly Ruchi Soya)." },
  "HONASA": { name: "Honasa Consumer (Mamaearth)", sector: "FMCG", about: "Digital-first personal-care company behind Mamaearth." },
  "GODREJIND": { name: "Godrej Industries", sector: "FMCG", about: "Diversified Godrej Group holding — chemicals, FMCG, realty." },
  "ZYDUSWELL": { name: "Zydus Wellness", sector: "FMCG", about: "Maker of Complan, Glucon-D, Nycil and Everyuth." },
  "JUBLFOOD": { name: "Jubilant FoodWorks", sector: "Retail", about: "Operator of Domino's Pizza and Popeyes in India." },
  "DEVYANI": { name: "Devyani International", sector: "Retail", about: "Largest KFC and Pizza Hut franchisee in India." },
  "SAPPHIRE": { name: "Sapphire Foods India", sector: "Retail", about: "KFC and Pizza Hut franchise operator." },
  "WESTLIFE": { name: "Westlife Foodworld", sector: "Retail", about: "Operator of McDonald's in West and South India." },
  "KALYANKJIL": { name: "Kalyan Jewellers India", sector: "Retail", about: "Pan-India jewellery retail chain." },
  "MANYAVAR": { name: "Vedant Fashions (Manyavar)", sector: "Retail", about: "Celebration and ethnic-wear retailer." },
  "METROBRAND": { name: "Metro Brands", sector: "Retail", about: "Footwear retailer (Metro, Mochi, Crocs)." },
  "CAMPUS": { name: "Campus Activewear", sector: "Retail", about: "Sports and athleisure footwear brand." },
  "INDIACEM": { name: "The India Cements", sector: "Cement", about: "South India-focused cement maker (UltraTech-controlled)." },
  "NUVOCO": { name: "Nuvoco Vistas", sector: "Cement", about: "Cement and building-materials maker (Nirma Group)." },
  "BIRLACORPN": { name: "Birla Corporation", sector: "Cement", about: "Cement and jute maker, MP Birla Group." },
  "JKLAKSHMI": { name: "JK Lakshmi Cement", sector: "Cement", about: "North and West India-focused cement maker." },
  "PRSMJOHNSN": { name: "Prism Johnson", sector: "Cement", about: "Cement, tiles (RAK) and ready-mix concrete maker." },
  "ASTRAL": { name: "Astral", sector: "Consumer", about: "Pipes, adhesives and building-products maker." },
  "SUPREMEIND": { name: "Supreme Industries", sector: "Consumer", about: "India's largest plastic-piping and products maker." },
  "FINPIPE": { name: "Finolex Industries", sector: "Consumer", about: "PVC pipes and resin manufacturer." },
  "CERA": { name: "Cera Sanitaryware", sector: "Consumer", about: "Sanitaryware, faucets and tiles maker." },
  "KAJARIACER": { name: "Kajaria Ceramics", sector: "Consumer", about: "India's largest ceramic-tiles manufacturer." },
  "JSL": { name: "Jindal Stainless", sector: "Metals", about: "India's largest stainless-steel producer." },
  "WELCORP": { name: "Welspun Corp", sector: "Metals", about: "Line-pipe and steel-products maker." },
  "LLOYDSME": { name: "Lloyds Metals & Energy", sector: "Metals", about: "Iron-ore mining and sponge-iron producer." },
  "HINDCOPPER": { name: "Hindustan Copper", sector: "Metals", about: "State-owned integrated copper producer." },
  "MOIL": { name: "MOIL", sector: "Metals", about: "State-owned manganese-ore miner." },
  "GRAVITA": { name: "Gravita India", sector: "Metals", about: "Lead and metals recycling company." },
  "APLLTD": { name: "Alembic Pharmaceuticals", sector: "Pharma", about: "Vertically integrated generics pharma company." },
  "CLEAN": { name: "Clean Science and Technology", sector: "Chemicals", about: "Specialty-chemicals maker with green chemistry focus." },
  "FINEORG": { name: "Fine Organic Industries", sector: "Chemicals", about: "World's leading oleochemical-based additives maker." },
  "VINATIORGA": { name: "Vinati Organics", sector: "Chemicals", about: "Specialty-chemicals maker (ATBS, IBB)." },
  "ALKYLAMINE": { name: "Alkyl Amines Chemicals", sector: "Chemicals", about: "Aliphatic amines and derivatives manufacturer." },
  "SUMICHEM": { name: "Sumitomo Chemical India", sector: "Chemicals", about: "Agrochemicals and crop-protection maker." },
  "SUDARSCHEM": { name: "Sudarshan Chemical Industries", sector: "Chemicals", about: "World's fourth-largest pigments manufacturer." },
  "HONAUT": { name: "Honeywell Automation India", sector: "Infra", about: "Industrial-automation and building-technology solutions." },
  "KEC": { name: "KEC International", sector: "Infra", about: "Power-transmission and infrastructure EPC company (RPG)." },
  "KALPATPOWR": { name: "Kalpataru Projects International", sector: "Infra", about: "Power-transmission, buildings and infrastructure EPC." },
  "NCC": { name: "NCC", sector: "Infra", about: "Diversified construction and infrastructure company." },
  "ENGINERSIN": { name: "Engineers India", sector: "Infra", about: "State-owned engineering-consultancy and EPC firm." },
  "IRCON": { name: "Ircon International", sector: "Infra", about: "State-owned railway and infrastructure construction company." },
  "RITES": { name: "RITES", sector: "Infra", about: "State-owned transport-infrastructure consultancy." },
  "TITAGARH": { name: "Titagarh Rail Systems", sector: "Infra", about: "Rail wagons, coaches and metro-train maker." },
  "JWL": { name: "Jupiter Wagons", sector: "Infra", about: "Railway wagons, brake systems and EV maker." },
  "PRAJIND": { name: "Praj Industries", sector: "Infra", about: "Bio-energy, ethanol and process-engineering company." },
  "AIAENG": { name: "AIA Engineering", sector: "Infra", about: "High-chrome grinding-media and wear-parts maker." },
  "GRINDWELL": { name: "Grindwell Norton", sector: "Infra", about: "Abrasives and ceramics maker (Saint-Gobain)." },
  "SKFINDIA": { name: "SKF India", sector: "Auto", about: "Bearings and rotating-equipment maker." },
  "BRIGADE": { name: "Brigade Enterprises", sector: "Realty", about: "Bengaluru-based diversified real-estate developer." },
  "SOBHA": { name: "Sobha", sector: "Realty", about: "Premium residential real-estate developer." },
  "MAHLIFE": { name: "Mahindra Lifespace Developers", sector: "Realty", about: "Real-estate and industrial-cluster developer (Mahindra)." },
  "SUNTECK": { name: "Sunteck Realty", sector: "Realty", about: "Mumbai-focused premium real-estate developer." },
  "SIGNATURE": { name: "Signatureglobal (India)", sector: "Realty", about: "Affordable and mid-income housing developer in NCR." },
  "NLCINDIA": { name: "NLC India", sector: "Power", about: "State-owned lignite mining and power-generation company." },
  "SUZLON": { name: "Suzlon Energy", sector: "Power", about: "Wind-turbine maker and renewable-energy solutions." },
  "INOXWIND": { name: "Inox Wind", sector: "Power", about: "Wind-energy equipment and solutions provider." },
  "KPIGREEN": { name: "KPI Green Energy", sector: "Power", about: "Solar and hybrid renewable-power developer." },
  "POWERINDIA": { name: "Hitachi Energy India", sector: "Power", about: "Power-grid technology and transformers maker." },
  "GENUSPOWER": { name: "Genus Power Infrastructures", sector: "Power", about: "Smart-meter and power-infrastructure maker." },
  "TATACOMM": { name: "Tata Communications", sector: "Telecom", about: "Global connectivity and digital-infrastructure provider." },
  "HFCL": { name: "HFCL", sector: "Telecom", about: "Optical-fibre and telecom-equipment maker." },
  "TEJASNET": { name: "Tejas Networks", sector: "Telecom", about: "Optical and data-networking products maker (Tata)." },
  "SAREGAMA": { name: "Saregama India", sector: "Media", about: "Music-content and IP company (RPG Group)." },
  "NAZARA": { name: "Nazara Technologies", sector: "Media", about: "Gaming and interactive-entertainment company." },
  "TIPSMUSIC": { name: "Tips Music", sector: "Media", about: "Music-label and content-licensing company." },
  "KPRMILL": { name: "K.P.R. Mill", sector: "Textiles", about: "Vertically integrated textiles and apparel maker." },
  "VARDHMAN": { name: "Vardhman Textiles", sector: "Textiles", about: "Yarn, fabric and textiles manufacturer." },
  "GOKEX": { name: "Gokaldas Exports", sector: "Textiles", about: "Apparel manufacturer and garment exporter." },
  "LUXIND": { name: "Lux Industries", sector: "Textiles", about: "Innerwear and hosiery brand." },
  "GOLDBEES": { name: "Nippon India Gold ETF", sector: "Commodities", about: "Exchange-traded fund that tracks the domestic price of physical gold." },
  "SILVERBEES": { name: "Nippon India Silver ETF", sector: "Commodities", about: "Exchange-traded fund that tracks the domestic price of physical silver." },
  "SETFGOLD": { name: "SBI Gold ETF", sector: "Commodities", about: "Gold exchange-traded fund from SBI Mutual Fund." },
  "HDFCGOLD": { name: "HDFC Gold ETF", sector: "Commodities", about: "Gold exchange-traded fund from HDFC Mutual Fund." },
  "AXISGOLD": { name: "Axis Gold ETF", sector: "Commodities", about: "Gold exchange-traded fund from Axis Mutual Fund." },
  "ICICIGOLD": { name: "ICICI Prudential Gold ETF", sector: "Commodities", about: "Gold exchange-traded fund from ICICI Prudential Mutual Fund." },
  "HDFCSILVER": { name: "HDFC Silver ETF", sector: "Commodities", about: "Silver exchange-traded fund from HDFC Mutual Fund." },
  "ICICISILVER": { name: "ICICI Prudential Silver ETF", sector: "Commodities", about: "Silver exchange-traded fund from ICICI Prudential Mutual Fund." },
  "SUNDARMFIN": { name: "Sundaram Finance", sector: "Finance", about: "Vehicle and asset-finance NBFC from the TVS Group." },
  "CREDITACC": { name: "CreditAccess Grameen", sector: "Finance", about: "India's largest NBFC-microfinance institution." },
  "AAVAS": { name: "Aavas Financiers", sector: "Finance", about: "Affordable housing-finance company." },
  "HOMEFIRST": { name: "Home First Finance", sector: "Finance", about: "Technology-led affordable housing-finance company." },
  "FIVESTAR": { name: "Five Star Business Finance", sector: "Finance", about: "Small-business secured lending NBFC." },
  "MFSL": { name: "Max Financial Services", sector: "Insurance", about: "Holding company of Max Life Insurance." },
  "UTIAMC": { name: "UTI Asset Management", sector: "Finance", about: "One of India's oldest mutual-fund managers." },
  "NUVAMA": { name: "Nuvama Wealth Management", sector: "Finance", about: "Wealth and asset-management firm (formerly Edelweiss Wealth)." },
  "DCBBANK": { name: "DCB Bank", sector: "Banking", about: "Private-sector bank focused on retail and SME lending." },
  "TMB": { name: "Tamilnad Mercantile Bank", sector: "Banking", about: "Old private-sector bank based in Tamil Nadu." },
  "PSB": { name: "Punjab & Sind Bank", sector: "Banking", about: "State-owned public-sector bank." },
  "SANOFI": { name: "Sanofi India", sector: "Pharma", about: "Indian arm of Sanofi — prescription drugs and vaccines." },
  "ERIS": { name: "Eris Lifesciences", sector: "Pharma", about: "Branded-formulations pharma company in chronic therapies." },
  "SUVENPHAR": { name: "Suven Pharmaceuticals", sector: "Pharma", about: "Contract development and manufacturing (CDMO) company." },
  "WOCKPHARMA": { name: "Wockhardt", sector: "Pharma", about: "Research-driven pharma company developing novel antibiotics." },
  "MEDANTA": { name: "Global Health (Medanta)", sector: "Healthcare", about: "Super-speciality hospital network under the Medanta brand." },
  "ASTERDM": { name: "Aster DM Healthcare", sector: "Healthcare", about: "Hospital and healthcare provider across India and GCC." },
  "KIMS": { name: "Krishna Institute of Medical Sciences", sector: "Healthcare", about: "Multi-speciality hospital chain in South India." },
  "RAINBOW": { name: "Rainbow Children's Medicare", sector: "Healthcare", about: "Paediatric and women's-health hospital chain." },
  "POLYMED": { name: "Poly Medicure", sector: "Healthcare", about: "Medical-devices and disposables manufacturer." },
  "JUSTDIAL": { name: "Just Dial", sector: "New Age", about: "Local search and business-listing platform (Reliance-owned)." },
  "IXIGO": { name: "Le Travenues Technology (ixigo)", sector: "New Age", about: "Online travel-booking platform for trains, flights and buses." },
  "TBOTEK": { name: "TBO Tek", sector: "New Age", about: "B2B travel-distribution technology platform." },
  "FIRSTCRY": { name: "Brainbees Solutions (FirstCry)", sector: "New Age", about: "Kids and baby products omnichannel retailer." },
  "LATENTVIEW": { name: "LatentView Analytics", sector: "IT", about: "Data-analytics and data-science services company." },
  "TANLA": { name: "Tanla Platforms", sector: "IT", about: "Cloud-communications (CPaaS) platform provider." },
  "ROUTE": { name: "Route Mobile", sector: "IT", about: "Cloud-communications and messaging platform." },
  "NEWGEN": { name: "Newgen Software Technologies", sector: "IT", about: "Low-code digital-automation and content-management software." },
  "ECLERX": { name: "eClerx Services", sector: "IT", about: "Data-management and business-process outsourcing company." },
  "FSL": { name: "Firstsource Solutions", sector: "IT", about: "Business-process management and outsourcing company (RP-Sanjiv Goenka)." },
  "HINDPETRO": { name: "Hindustan Petroleum", sector: "Energy", about: "Maharatna PSU oil refining and marketing company." },
  "OIL": { name: "Oil India", sector: "Energy", about: "State-owned crude oil and natural-gas explorer." },
  "GUJGASLTD": { name: "Gujarat Gas", sector: "Energy", about: "India's largest city gas distribution company." },
  "GSPL": { name: "Gujarat State Petronet", sector: "Energy", about: "Natural-gas transmission company in Gujarat." },
  "ATGL": { name: "Adani Total Gas", sector: "Energy", about: "City gas distribution JV of Adani and TotalEnergies." },
  "CASTROLIND": { name: "Castrol India", sector: "Energy", about: "Automotive and industrial lubricants maker." },
  "AEGISLOG": { name: "Aegis Logistics", sector: "Energy", about: "Oil, gas and chemical logistics and storage company." },
  "GESHIP": { name: "Great Eastern Shipping", sector: "Energy", about: "India's largest private-sector shipping company." },
  "CHAMBLFERT": { name: "Chambal Fertilisers & Chemicals", sector: "Chemicals", about: "Urea and crop-nutrient manufacturer." },
  "GSFC": { name: "Gujarat State Fertilizers & Chemicals", sector: "Chemicals", about: "Fertilizers and industrial-chemicals maker." },
  "DEEPAKFERT": { name: "Deepak Fertilisers & Petrochemicals", sector: "Chemicals", about: "Fertilizers, industrial chemicals and mining chemicals maker." },
  "EIDPARRY": { name: "EID Parry (India)", sector: "Chemicals", about: "Sugar and nutraceuticals maker; parent of Coromandel." },
  "NOCIL": { name: "NOCIL", sector: "Chemicals", about: "India's largest rubber-chemicals manufacturer." },
  "BALAMINES": { name: "Balaji Amines", sector: "Chemicals", about: "Aliphatic amines and specialty chemicals maker." },
  "NEOGEN": { name: "Neogen Chemicals", sector: "Chemicals", about: "Bromine and lithium specialty-chemicals maker." },
  "SUPRAJIT": { name: "Suprajit Engineering", sector: "Auto", about: "Automotive cables and actuation-systems maker." },
  "SANSERA": { name: "Sansera Engineering", sector: "Auto", about: "Precision forged and machined auto components." },
  "CRAFTSMAN": { name: "Craftsman Automation", sector: "Auto", about: "Powertrain, aluminium and industrial-engineering products." },
  "GABRIEL": { name: "Gabriel India", sector: "Auto", about: "Ride-control products (shock absorbers) maker (Anand Group)." },
  "ELGIEQUIP": { name: "Elgi Equipments", sector: "Infra", about: "Air-compressors and automotive-equipment manufacturer." },
  "TIMKEN": { name: "Timken India", sector: "Auto", about: "Bearings and mechanical power-transmission maker." },
  "CARBORUNIV": { name: "Carborundum Universal", sector: "Infra", about: "Abrasives, ceramics and electrominerals maker (Murugappa)." },
  "KIRLOSENG": { name: "Kirloskar Oil Engines", sector: "Infra", about: "Diesel engines, gensets and pumps manufacturer." },
  "IRB": { name: "IRB Infrastructure Developers", sector: "Infra", about: "Highways and roads BOT developer and operator." },
  "HGINFRA": { name: "H.G. Infra Engineering", sector: "Infra", about: "Roads, highways and infrastructure EPC company." },
  "PNCINFRA": { name: "PNC Infratech", sector: "Infra", about: "Highways and infrastructure construction company." },
  "KNRCON": { name: "KNR Constructions", sector: "Infra", about: "Roads, irrigation and urban-infrastructure EPC company." },
  "GRINFRA": { name: "G R Infraprojects", sector: "Infra", about: "Integrated roads and highways EPC company." },
  "POWERMECH": { name: "Power Mech Projects", sector: "Infra", about: "Power-plant erection and O&M services company." },
  "TRITURBINE": { name: "Triveni Turbine", sector: "Infra", about: "Industrial steam-turbine manufacturer." },
  "KOLTEPATIL": { name: "Kolte-Patil Developers", sector: "Realty", about: "Pune and Mumbai-focused real-estate developer." },
  "PURVA": { name: "Puravankara", sector: "Realty", about: "Bengaluru-based residential real-estate developer." },
  "ANANTRAJ": { name: "Anant Raj", sector: "Realty", about: "NCR real-estate and data-centre developer." },
  "GODFRYPHLP": { name: "Godfrey Phillips India", sector: "FMCG", about: "Cigarettes and FMCG company (Modi Group)." },
  "VSTIND": { name: "VST Industries", sector: "FMCG", about: "Cigarettes and leaf-tobacco company." },
  "HATSUN": { name: "Hatsun Agro Product", sector: "FMCG", about: "India's largest private-sector dairy company (Arun, Arokya)." },
  "CCL": { name: "CCL Products (India)", sector: "FMCG", about: "World's largest private-label instant-coffee manufacturer." },
  "BIKAJI": { name: "Bikaji Foods International", sector: "FMCG", about: "Packaged ethnic-snacks and sweets maker." },
  "SENCO": { name: "Senco Gold", sector: "Retail", about: "Eastern-India-focused jewellery retail chain." },
  "GOCOLORS": { name: "Go Fashion (India)", sector: "Retail", about: "Women's bottom-wear retailer (Go Colors)." },
  "STLTECH": { name: "Sterlite Technologies", sector: "Telecom", about: "Optical-fibre and digital-network solutions maker." },
  "ITI": { name: "ITI Limited", sector: "Telecom", about: "State-owned telecom-equipment manufacturer." },
  "PTCIL": { name: "PTC Industries", sector: "Defence", about: "Titanium and superalloy castings maker for aerospace and defence." },
  "ZENTEC": { name: "Zen Technologies", sector: "Defence", about: "Defence training simulators and anti-drone systems maker." },
  "IDEAFORGE": { name: "ideaForge Technology", sector: "Defence", about: "Unmanned-aerial-vehicle (drone) manufacturer." },
  "MOTILALOFS": { name: "Motilal Oswal Financial Services", sector: "Finance", about: "Broking, wealth and asset-management financial-services group." },
  "JMFINANCIL": { name: "JM Financial", sector: "Finance", about: "Diversified financial-services and investment-banking group." },
  "ANANDRATHI": { name: "Anand Rathi Wealth", sector: "Finance", about: "Private wealth-management firm." },
  "CHOLAHLDNG": { name: "Cholamandalam Financial Holdings", sector: "Finance", about: "Murugappa Group financial-services holding company." },
  "ABSLAMC": { name: "Aditya Birla Sun Life AMC", sector: "Finance", about: "Asset manager behind Aditya Birla Sun Life Mutual Fund." },
  "SBFC": { name: "SBFC Finance", sector: "Finance", about: "Secured MSME and gold-loan NBFC." },
  "CSBBANK": { name: "CSB Bank", sector: "Banking", about: "Kerala-based private-sector bank." },
  "GODIGIT": { name: "Go Digit General Insurance", sector: "Insurance", about: "Digital-first general insurer." },
  "NIVABUPA": { name: "Niva Bupa Health Insurance", sector: "Insurance", about: "Standalone health-insurance company." },
  "JUBLPHARMA": { name: "Jubilant Pharmova", sector: "Pharma", about: "Integrated pharma and life-sciences company." },
  "CONCORDBIO": { name: "Concord Biotech", sector: "Pharma", about: "Fermentation-based API and biopharma maker." },
  "SUPRIYA": { name: "Supriya Lifescience", sector: "Pharma", about: "Active-pharmaceutical-ingredient (API) manufacturer." },
  "MARKSANS": { name: "Marksans Pharma", sector: "Pharma", about: "Generic-formulations maker focused on regulated markets." },
  "VIJAYA": { name: "Vijaya Diagnostic Centre", sector: "Healthcare", about: "South-India-focused diagnostics chain." },
  "FDC": { name: "FDC Limited", sector: "Pharma", about: "Branded-formulations maker (Electral, Zifi)." },
  "FLUOROCHEM": { name: "Gujarat Fluorochemicals", sector: "Chemicals", about: "Fluoropolymers, refrigerants and battery-chemicals maker." },
  "PCBL": { name: "PCBL Limited", sector: "Chemicals", about: "World-scale carbon-black manufacturer (RP-Sanjiv Goenka)." },
  "JUBLINGREA": { name: "Jubilant Ingrevia", sector: "Chemicals", about: "Life-science ingredients and specialty-chemicals maker." },
  "ARCHEAN": { name: "Archean Chemical Industries", sector: "Chemicals", about: "Bromine, industrial salt and marine-chemicals maker." },
  "GPIL": { name: "Godawari Power & Ispat", sector: "Metals", about: "Integrated iron-ore pellet and steel producer." },
  "SHYAMMETL": { name: "Shyam Metalics & Energy", sector: "Metals", about: "Integrated metal producer — steel, ferro-alloys, aluminium foil." },
  "ELECTCAST": { name: "Electrosteel Castings", sector: "Metals", about: "Ductile-iron pipes and castings maker." },
  "APARINDS": { name: "Apar Industries", sector: "Infra", about: "Conductors, transformer oils and specialty cables maker." },
  "VGUARD": { name: "V-Guard Industries", sector: "Consumer", about: "Electricals and consumer-durables maker." },
  "FINCABLES": { name: "Finolex Cables", sector: "Consumer", about: "Electrical and communication cables maker." },
  "RRKABEL": { name: "R R Kabel", sector: "Consumer", about: "Wires, cables and consumer-electrical products maker." },
  "ELECON": { name: "Elecon Engineering", sector: "Infra", about: "Industrial gears and material-handling equipment maker." },
  "SYMPHONY": { name: "Symphony", sector: "Consumer", about: "Air-cooler maker with global operations." },
  "TTKPRESTIG": { name: "TTK Prestige", sector: "Consumer", about: "Kitchen and home-appliances maker." },
  "VIPIND": { name: "VIP Industries", sector: "Consumer", about: "Luggage and travel-gear maker (VIP, Skybags)." },
  "SAFARI": { name: "Safari Industries", sector: "Consumer", about: "Fast-growing luggage and travel-goods maker." },
  "CELLO": { name: "Cello World", sector: "Consumer", about: "Consumer houseware, writing instruments and moulded furniture." },
  "WAAREE": { name: "Waaree Energies", sector: "Power", about: "India's largest solar-PV module manufacturer." },
  "PREMIERENE": { name: "Premier Energies", sector: "Power", about: "Solar-cell and module manufacturer." },
  "NTPCGREEN": { name: "NTPC Green Energy", sector: "Power", about: "Renewable-energy arm of NTPC." },
  "JYOTICNC": { name: "Jyoti CNC Automation", sector: "Infra", about: "CNC machine-tools manufacturer." },
  "ATHERENERG": { name: "Ather Energy", sector: "New Age", about: "Electric two-wheeler manufacturer." },
  "INDHOTEL": { name: "The Indian Hotels Company", sector: "Hospitality", about: "Taj-brand luxury and business hotels operator." },
  "EIHOTEL": { name: "EIH Limited", sector: "Hospitality", about: "Oberoi and Trident luxury hotels operator." },
  "LEMONTREE": { name: "Lemon Tree Hotels", sector: "Hospitality", about: "Mid-market and upscale hotels chain." },
  "CHALET": { name: "Chalet Hotels", sector: "Hospitality", about: "Owner of premium hotels across major Indian cities." },
  "JUNIPER": { name: "Juniper Hotels", sector: "Hospitality", about: "Hyatt-affiliated luxury and upper-upscale hotels owner." },
  "WABAG": { name: "VA Tech Wabag", sector: "Infra", about: "Water and wastewater treatment technology company." },
  "AZAD": { name: "Azad Engineering", sector: "Defence", about: "Precision components for aerospace, defence and energy turbines." },
  "HBLENGINE": { name: "HBL Engineering", sector: "Defence", about: "Specialised batteries and railway-electronics (Kavach) maker." },
  "INOXINDIA": { name: "INOX India", sector: "Infra", about: "Cryogenic equipment and storage-tanks manufacturer." },
  "SWSOLAR": { name: "Sterling & Wilson Renewable Energy", sector: "Power", about: "Solar EPC and O&M solutions provider." },
  "ORIENTELEC": { name: "Orient Electric", sector: "Consumer", about: "Fans, lighting and home-appliances maker (CK Birla Group)." },
  "SAGILITY": { name: "Sagility India", sector: "IT", about: "Healthcare-focused business-process-management services." },
  "JINDALSAW": { name: "Jindal Saw", sector: "Metals", about: "Iron and steel pipes and pellets manufacturer." },
  "MAHSEAMLES": { name: "Maharashtra Seamless", sector: "Metals", about: "Seamless and ERW steel pipes maker (Jindal D.P. Group)." },
  "USHAMART": { name: "Usha Martin", sector: "Metals", about: "World's leading steel-wire-rope manufacturer." },
  "KSB": { name: "KSB Limited", sector: "Infra", about: "Pumps and industrial valves manufacturer." },
  "KIRLOSBROS": { name: "Kirloskar Brothers", sector: "Infra", about: "India's largest fluid-management and pumps company." },
  "PTC": { name: "PTC India", sector: "Power", about: "India's leading power-trading company." },
  "TRIVENI": { name: "Triveni Engineering & Industries", sector: "FMCG", about: "Sugar, ethanol and engineering conglomerate." },
  "BALRAMCHIN": { name: "Balrampur Chini Mills", sector: "FMCG", about: "One of India's largest integrated sugar and ethanol producers." },
  "JISLJALEQS": { name: "Jain Irrigation Systems", sector: "Infra", about: "Micro-irrigation systems and agri-inputs company." },
  "ZFCVINDIA": { name: "ZF Commercial Vehicle Control Systems", sector: "Auto", about: "Braking and control systems for commercial vehicles." },
  "SCHNEIDER": { name: "Schneider Electric Infrastructure", sector: "Infra", about: "Medium-voltage and grid-automation equipment maker." },
  "INDIASHLTR": { name: "India Shelter Finance", sector: "Finance", about: "Affordable housing-finance company for self-employed borrowers." },
};
